"""Alcatrax's curated, evidence-bounded knowledge brain.

This module is data maintained by Alcatrax, never generated by Scout. A
capability says what Alcatrax can offer; a solution pattern is a reusable
solution shape; a past project is proof only for the patterns/capabilities it
explicitly records. Unknown project detail intentionally remains unknown.
"""
from __future__ import annotations

from dataclasses import dataclass, field


MATURITY_STATES = ("proven", "demonstrated", "developing")


@dataclass(frozen=True)
class Capability:
    id: str
    name: str
    description: str
    solves: list[str]
    maturity: str = "developing"
    proof_notes: str = ""


@dataclass(frozen=True)
class SolutionPattern:
    """Reusable solution type, distinct from both a capability and a client."""
    id: str
    name: str
    description: str
    problem_tags: list[str]
    capability_ids: list[str]
    relevant_project_ids: list[str]


@dataclass(frozen=True)
class PastProject:
    id: str
    client_name: str
    industry: str = "unknown"
    # Retained for callers from the original Phase 1 knowledge structure.
    problem_solved: str = ""
    capabilities_used: list[str] = field(default_factory=list)
    url: str = ""
    notes: str = ""
    status: str = "unknown"
    business_problems: list[str] = field(default_factory=list)
    solution_delivered: str = ""
    features: list[str] = field(default_factory=list)
    solution_pattern_ids: list[str] = field(default_factory=list)
    proof_notes: str = ""


# Existing stable IDs are preserved. Maturity describes the strength of the
# catalogue's proof, not an assertion that every capability has client proof.
CAPABILITIES: list[Capability] = [
    Capability("websites", "Business websites", "Marketing and informational websites.",
               ["no_website", "outdated_site", "poor_mobile_ux", "weak_trust_signals", "weak_digital_presence"],
               "proven", "Demonstrated by the recorded public website projects."),
    Capability("ecommerce", "Ecommerce / digital showrooms", "Online product discovery and commerce flows.",
               ["no_online_ordering", "no_catalogue", "instagram_only_sales", "poor_product_discovery"],
               "proven", "4WD Spare Parts Kenya is recorded as an ecommerce project."),
    Capability("catalogue", "Digital catalogues", "Searchable product or service catalogues without requiring checkout.",
               ["no_catalogue", "instagram_only_sales", "poor_seo", "poor_product_discovery"],
               "proven", "Recorded automotive catalogue projects provide direct examples."),
    Capability("inventory", "Inventory / product management", "Stock and product-management systems.",
               ["manual_stock_tracking", "no_catalogue"], "developing"),
    Capability("booking", "Booking systems", "Appointment and reservation flows.",
               ["manual_booking", "phone_only_booking"], "developing"),
    Capability("dashboards", "Operational dashboards", "Reporting and control interfaces for daily decisions.",
               ["no_reporting_visibility"], "developing"),
    Capability("crm", "CRM / customer portals", "Customer relationship tracking and private portals.",
               ["no_lead_tracking", "manual_followup"], "developing"),
    Capability("admin_systems", "Admin / business management systems", "Internal systems for business administration.",
               ["manual_business_management", "fragmented_operations"], "developing"),
    Capability("analytics", "Analytics", "Measurement and reporting foundations for digital operations.",
               ["no_reporting_visibility", "weak_measurement"], "developing"),
    Capability("seo", "SEO", "Search-oriented content and metadata architecture.",
               ["poor_seo", "weak_search_visibility"], "developing"),
    Capability("geo_ai_search", "GEO / AI-search optimization", "Content structure for generative and AI-assisted search discovery.",
               ["weak_ai_search_visibility", "weak_search_visibility"], "developing"),
    Capability("whatsapp", "WhatsApp/customer-contact integration", "Contextual WhatsApp contact and enquiry flows.",
               ["no_whatsapp_flow", "manual_followup"], "developing"),
    Capability("database_apps", "Database-backed applications", "Applications with durable structured data.",
               ["spreadsheet_dependency", "fragmented_data"], "developing"),
    Capability("cloud_deployment", "Cloud deployment", "Deployment foundations for web applications.",
               ["no_reliable_deployment"], "developing"),
    Capability("automation", "Business automation", "Workflow automation for repetitive business work.",
               ["manual_followup", "manual_stock_tracking"], "developing"),
    Capability("custom_software", "Custom software", "Purpose-built business software.",
               ["manual_business_management", "fragmented_operations"], "developing"),
    Capability("ai_agents", "AI agents", "Custom agents for business-specific tasks.",
               ["manual_research", "manual_followup"], "demonstrated",
               "Scout itself is not treated as a proven client deployment."),
]


# Records use only the original catalogue's stated project descriptions. The
# two newly named projects are intentionally present but unmapped until factual
# project information is supplied.
PAST_PROJECTS: list[PastProject] = [
    PastProject("space-motors", "Space Motors", "automotive_spare_parts",
                "Auto spare parts catalogue/website", ["websites", "catalogue"],
                "https://www.spacemotorsparesltd.co.ke/", status="public_url_recorded",
                business_problems=["no_catalogue", "poor_product_discovery"],
                solution_delivered="Auto spare parts catalogue/website",
                solution_pattern_ids=["automotive_digital_catalogue", "business_web_presence"]),
    PastProject("lucky-line", "Lucky Line Autospares", "automotive_spare_parts",
                "Auto parts website", ["websites", "catalogue"],
                "https://luckylineautospares.co.ke/", status="public_url_recorded",
                business_problems=["no_catalogue", "poor_product_discovery"],
                solution_delivered="Auto parts website",
                solution_pattern_ids=["automotive_digital_catalogue", "business_web_presence"]),
    PastProject("formula3", "Formula3 Autospares", "automotive_spare_parts",
                "Auto spare parts catalogue", ["websites", "catalogue"],
                "https://formula3autospares.co.ke/", status="public_url_recorded",
                business_problems=["no_catalogue", "poor_product_discovery"],
                solution_delivered="Auto spare parts catalogue",
                solution_pattern_ids=["automotive_digital_catalogue", "business_web_presence"]),
    PastProject("4wd-spareparts", "4WD Spare Parts Kenya", "automotive_spare_parts",
                "4x4 parts ecommerce", ["websites", "ecommerce", "catalogue"],
                "https://www.4wdspareparts.co.ke/", status="public_url_recorded",
                business_problems=["no_online_ordering", "no_catalogue", "poor_product_discovery"],
                solution_delivered="4x4 parts ecommerce",
                solution_pattern_ids=["automotive_digital_catalogue", "ecommerce_store", "business_web_presence"]),
    PastProject("magda-auto-hub", "Magda Auto Hub", "automotive_dealership",
                "Car dealership showroom", ["websites", "catalogue"],
                "https://magdaautohub.co.ke/", status="public_url_recorded",
                business_problems=["no_catalogue", "poor_product_discovery"],
                solution_delivered="Car dealership showroom",
                solution_pattern_ids=["digital_showroom", "business_web_presence"]),
    PastProject("karanis-ec-bv-motors", "Karani's EC & BV Motors"),
    PastProject("weru-interiors", "Weru Interiors"),
]


SOLUTION_PATTERNS: list[SolutionPattern] = [
    SolutionPattern("automotive_digital_catalogue", "Automotive digital catalogue",
                    "A browsable automotive parts catalogue for product discovery.",
                    ["no_catalogue", "poor_product_discovery"], ["websites", "catalogue"],
                    ["space-motors", "lucky-line", "formula3", "4wd-spareparts"]),
    SolutionPattern("digital_showroom", "Digital showroom",
                    "A browsable online showroom for a product/listing business.",
                    ["no_catalogue", "poor_product_discovery"], ["websites", "catalogue"],
                    ["magda-auto-hub"]),
    SolutionPattern("ecommerce_store", "Ecommerce store",
                    "Online product discovery with an ecommerce flow.",
                    ["no_online_ordering", "no_catalogue"], ["websites", "catalogue", "ecommerce"],
                    ["4wd-spareparts"]),
    SolutionPattern("business_web_presence", "Business web presence",
                    "A public business website for a clearer digital presence.",
                    ["no_website", "outdated_site", "weak_digital_presence"], ["websites"],
                    ["space-motors", "lucky-line", "formula3", "4wd-spareparts", "magda-auto-hub"]),
]


def _by_id(items):
    return {item.id: item for item in items}


def capability_by_id(capability_id: str) -> Capability | None:
    return _by_id(CAPABILITIES).get(capability_id)


def project_by_id(project_id: str) -> PastProject | None:
    return _by_id(PAST_PROJECTS).get(project_id)


def project_by_identifier(identifier: str) -> PastProject | None:
    return project_by_id(identifier) or next((p for p in PAST_PROJECTS if p.client_name == identifier), None)


def pattern_by_id(pattern_id: str) -> SolutionPattern | None:
    return _by_id(SOLUTION_PATTERNS).get(pattern_id)


def capability_exists(capability_id: str) -> bool:
    return capability_by_id(capability_id) is not None


def project_exists(identifier: str) -> bool:
    return project_by_identifier(identifier) is not None


def pattern_exists(pattern_id: str) -> bool:
    return pattern_by_id(pattern_id) is not None


def pattern_includes_capability(pattern_id: str, capability_id: str) -> bool:
    pattern = pattern_by_id(pattern_id)
    return bool(pattern and capability_id in pattern.capability_ids)


def project_demonstrates_capability(project_identifier: str, capability_id: str) -> bool:
    project = project_by_identifier(project_identifier)
    return bool(project and capability_id in project.capabilities_used)


def project_supports_pattern(project_identifier: str, pattern_id: str) -> bool:
    project = project_by_identifier(project_identifier)
    pattern = pattern_by_id(pattern_id)
    return bool(project and pattern and pattern_id in project.solution_pattern_ids and project.id in pattern.relevant_project_ids)


def projects_for_pattern(pattern_id: str) -> list[PastProject]:
    pattern = pattern_by_id(pattern_id)
    if not pattern:
        return []
    return [project_by_id(project_id) for project_id in pattern.relevant_project_ids if project_by_id(project_id)]


def patterns_for_problem(problem_tag: str) -> list[SolutionPattern]:
    return [pattern for pattern in SOLUTION_PATTERNS if problem_tag in pattern.problem_tags]


def capabilities_for_problem(problem_tag: str) -> list[Capability]:
    return [capability for capability in CAPABILITIES if problem_tag in capability.solves]


def reference_projects_for_industry(industry: str) -> list[PastProject]:
    return [project for project in PAST_PROJECTS if project.industry == industry]


def catalogue_integrity_errors() -> list[str]:
    """Return deterministic errors; tests call this to protect curated data."""
    errors: list[str] = []
    for label, items in (("capability", CAPABILITIES), ("project", PAST_PROJECTS), ("pattern", SOLUTION_PATTERNS)):
        ids = [item.id for item in items]
        if len(ids) != len(set(ids)):
            errors.append(f"duplicate {label} IDs")
    for project in PAST_PROJECTS:
        for capability_id in project.capabilities_used:
            if not capability_exists(capability_id):
                errors.append(f"project {project.id} references unknown capability {capability_id}")
        for pattern_id in project.solution_pattern_ids:
            if not pattern_exists(pattern_id):
                errors.append(f"project {project.id} references unknown pattern {pattern_id}")
    for pattern in SOLUTION_PATTERNS:
        for capability_id in pattern.capability_ids:
            if not capability_exists(capability_id):
                errors.append(f"pattern {pattern.id} references unknown capability {capability_id}")
        for project_id in pattern.relevant_project_ids:
            if not project_by_id(project_id):
                errors.append(f"pattern {pattern.id} references unknown project {project_id}")
            elif not project_supports_pattern(project_id, pattern.id):
                errors.append(f"pattern {pattern.id} and project {project_id} are not mutually linked")
    return errors


def assert_catalogue_integrity() -> None:
    errors = catalogue_integrity_errors()
    if errors:
        raise ValueError("Alcatrax knowledge catalogue is invalid: " + "; ".join(errors))


def as_prompt_context() -> str:
    cap_lines = "\n".join(
        f"- {cap.id}: {cap.name} [{cap.maturity}] -- {cap.description}" for cap in CAPABILITIES
    )
    pattern_lines = "\n".join(
        f"- {pattern.id}: {pattern.name}; problems={', '.join(pattern.problem_tags)}; "
        f"capabilities={', '.join(pattern.capability_ids)}; projects={', '.join(pattern.relevant_project_ids)}"
        for pattern in SOLUTION_PATTERNS
    )
    project_lines = "\n".join(
        f"- {project.id}: {project.client_name} ({project.industry}); "
        f"capabilities={', '.join(project.capabilities_used) or 'unknown'}; "
        f"patterns={', '.join(project.solution_pattern_ids) or 'unknown'}"
        for project in PAST_PROJECTS
    )
    return (
        f"ALCATRAX CAPABILITIES:\n{cap_lines}\n\nALCATRAX SOLUTION PATTERNS:\n{pattern_lines}\n\n"
        f"ALCATRAX PAST PROJECTS:\n{project_lines}\n\n"
        "Choose only listed IDs. A project is proof only when it is listed for the chosen pattern and "
        "demonstrates the chosen capability. Leave any unsupported reference empty."
    )
