from __future__ import annotations

"""Alcatrax's own capability catalogue and project history, as structured
data. This is what the opportunity engine grounds itself in -- an LLM given
this catalogue can say "reference: Karani's EC & BV Motors" instead of
inventing a plausible-sounding but fictional justification.

Everything here is DATA, edited by Dennis, not generated by any agent.
Scout reads this; it never writes to it. Keep it current as projects ship --
stale references here are worse than none (a fabricated confidence signal).
"""
from dataclasses import dataclass, field


@dataclass
class Capability:
    id: str
    name: str
    description: str
    solves: list[str]   # problem tags this capability addresses, e.g. "no_catalogue"


@dataclass
class PastProject:
    id: str
    client_name: str
    industry: str
    problem_solved: str
    capabilities_used: list[str]   # Capability ids
    url: str = ""
    notes: str = ""


CAPABILITIES: list[Capability] = [
    Capability("websites", "Business websites", "Marketing/informational websites, industry-tuned templates.",
               ["no_website", "outdated_site", "poor_mobile_ux", "weak_trust_signals"]),
    Capability("ecommerce", "Ecommerce / digital showrooms", "Full online shops with cart, checkout, M-Pesa-ready flows.",
               ["no_online_ordering", "no_catalogue", "instagram_only_sales"]),
    Capability("catalogue", "Digital catalogues", "Searchable product/service catalogues without full checkout.",
               ["no_catalogue", "instagram_only_sales", "poor_seo"]),
    Capability("inventory", "Inventory systems", "Stock tracking, admin panels for product/stock management.",
               ["manual_stock_tracking", "no_catalogue"]),
    Capability("booking", "Booking systems", "Appointment/reservation flows for service businesses.",
               ["manual_booking", "phone_only_booking"]),
    Capability("dashboards", "Operational dashboards", "Reporting/control-room interfaces for daily decisions.",
               ["no_reporting_visibility"]),
    Capability("crm", "CRM / customer portals", "Customer relationship tracking, private client-facing portals.",
               ["no_lead_tracking", "manual_followup"]),
    Capability("seo", "SEO-first architecture", "Structured content/metadata built for search visibility.",
               ["poor_seo", "weak_search_visibility"]),
    Capability("whatsapp", "WhatsApp integration", "Pre-filled contextual WhatsApp CTAs as a primary conversion path.",
               ["no_whatsapp_flow", "manual_followup"]),
    Capability("automation", "Business automation", "Removing manual follow-up work via workflow automation.",
               ["manual_followup", "manual_stock_tracking"]),
    Capability("ai_agents", "AI agents", "Custom AI agents for business-specific tasks (e.g. this very system).",
               ["manual_research", "manual_followup"]),
]

# Seed with what's publicly listed on alcatraxtechnologies.co.ke/projects as of
# this writing. Add the rest (Karani's EC & BV Motors, Weru Interiors, etc.)
# with their actual problem/capability mapping as you have it -- these are
# placeholders using only what's publicly visible, not invented outcomes.
PAST_PROJECTS: list[PastProject] = [
    PastProject("space-motors", "Space Motors", "automotive_spare_parts",
                "Auto spare parts catalogue/website", ["websites", "catalogue"],
                url="https://www.spacemotorsparesltd.co.ke/"),
    PastProject("lucky-line", "Lucky Line Autospares", "automotive_spare_parts",
                "Auto parts website", ["websites", "catalogue"],
                url="https://luckylineautospares.co.ke/"),
    PastProject("formula3", "Formula3 Autospares", "automotive_spare_parts",
                "Auto spare parts catalogue", ["websites", "catalogue"],
                url="https://formula3autospares.co.ke/"),
    PastProject("4wd-spareparts", "4WD Spare Parts Kenya", "automotive_spare_parts",
                "4x4 parts ecommerce", ["websites", "ecommerce", "catalogue"],
                url="https://www.4wdspareparts.co.ke/"),
    PastProject("magda-auto-hub", "Magda Auto Hub", "automotive_dealership",
                "Car dealership showroom", ["websites", "catalogue"],
                url="https://magdaautohub.co.ke/"),
]


def capabilities_for_problem(problem_tag: str) -> list[Capability]:
    return [c for c in CAPABILITIES if problem_tag in c.solves]


def reference_projects_for_industry(industry: str) -> list[PastProject]:
    return [p for p in PAST_PROJECTS if p.industry == industry]


def as_prompt_context() -> str:
    """Rendered for injection into the analyze.py LLM prompt, so the model
    reasons over real capabilities/projects instead of inventing plausible ones."""
    cap_lines = "\n".join(f"- {c.id}: {c.name} -- {c.description}" for c in CAPABILITIES)
    proj_lines = "\n".join(
        f"- {p.client_name} ({p.industry}): {p.problem_solved} [used: {', '.join(p.capabilities_used)}]"
        for p in PAST_PROJECTS
    )
    return (
        f"ALCATRAX CAPABILITIES:\n{cap_lines}\n\n"
        f"ALCATRAX PAST PROJECTS:\n{proj_lines}\n\n"
        "When recommending a solution, you MUST choose from the capability IDs "
        "listed above -- never invent a capability Alcatrax doesn't have. When "
        "citing a reference project, you MUST choose from the past projects "
        "listed above and only cite one whose industry or problem genuinely "
        "matches. If nothing matches, leave the reference empty rather than "
        "forcing a weak comparison."
    )
